### ISSUE TITLE
raise SizeMismatchError when training Detic Deformable DETR

### ISSUE THREAD

**Issue by parang99** [facebookresearch/Detic#25]
Hi @xingyizhou,  

I was trying to train with the Detic Deformable DETR model and it stopped with SizeMismatchError. 

There seems to be inconsistent information between the images from datasets/imagenet/ImageNet-LVIS and datasets/imagenet/annotations/imagenet_lvis_image_info.json

I think the error is related with image’s exif orientation information but I’m not sure about that. 
It will be very thankful if you check about this problem.

The command that I used was `python train_net.py --num-gpus 8 --config-file configs/Detic_DeformDETR_LI_R50_4x_ft4x.yaml 2>&1 | tee detr.log`

These are my settings. 
- torch : 1.8.2
- CUDA : 11.2
- python : 3.8.12   
     
Thanks, 
Janet

```
[02/11 10:48:15 d2.utils.events]: [eta: 1 day, 13:15:24  iter: 360  total_loss: 1.256e+04  loss_bbox: 0.1673  loss_bbox_0: 0.1682  loss_bbox_1: 0.1679  loss_bbox_2: 0.163  loss_bbox_3: 0.1675  loss_bbox_4: 0.1662  loss_bbox_enc: 0.0305  loss_ce: 0.4108  loss_ce_0: 0.5892  loss_ce_1: 0.5113  loss_ce_2: 0.4529  loss_ce_3: 0.4268  loss_ce_4: 0.4176  loss_ce_enc: 0.317  loss_giou: 0.6105  loss_giou_0: 0.6227  loss_giou_1: 0.6104  loss_giou_2: 0.6175  loss_giou_3: 0.6193  loss_giou_4: 0.6127  loss_giou_enc: 0.2911  loss_image: 1.953  time: 0.7772  data_time: 0.0368  lr: 0.0002  max_mem: 18412M
[02/11 10:48:31 d2.utils.events]: [eta: 1 day, 13:17:40  iter: 380  total_loss: 1.293e+04  loss_bbox: 0.1899  loss_bbox_0: 0.1976  loss_bbox_1: 0.1972  loss_bbox_2: 0.1936  loss_bbox_3: 0.1943  loss_bbox_4: 0.1916  loss_bbox_enc: 0.03412  loss_ce: 0.4291  loss_ce_0: 0.5788  loss_ce_1: 0.528  loss_ce_2: 0.4731  loss_ce_3: 0.4426  loss_ce_4: 0.4258  loss_ce_enc: 0.3217  loss_giou: 0.6712  loss_giou_0: 0.6713  loss_giou_1: 0.6773  loss_giou_2: 0.6799  loss_giou_3: 0.6807  loss_giou_4: 0.6768  loss_giou_enc: 0.2945  loss_image: 2.001  time: 0.7765  data_time: 0.0325  lr: 0.0002  max_mem: 18412M
Traceback (most recent call last):
  File "train_net.py", line 262, in <module>
    launch(
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 7 terminated with the following error:
Traceback (most recent call last):
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/user/Detic/train_net.py", line 240, in main
    do_train(cfg, model, resume=args.resume)
  File "/home/user/Detic/train_net.py", line 148, in do_train
    for data, iteration in zip(data_loader, range(start_iter, max_iter)):
  File "/home/user/Detic/detic/data/custom_dataset_dataloader.py", line 297, in __iter__
    for d in self.dataset:
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
detectron2.data.detection_utils.SizeMismatchError: Caught SizeMismatchError in DataLoader worker process 2.
Original Traceback (most recent call last):
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/detectron2/data/common.py", line 90, in __getitem__
    data = self._map_func(self._dataset[cur_idx])
  File "/home/user/Detic/detic/data/custom_dataset_mapper.py", line 96, in __call__
    utils.check_image_size(dataset_dict, ori_image)
  File "/home/user/.conda/envs/detic/lib/python3.8/site-packages/detectron2/data/detection_utils.py", line 196, in check_image_size
    raise SizeMismatchError(
detectron2.data.detection_utils.SizeMismatchError: Mismatched image shape for image datasets/imagenet/ImageNet-LVIS/n04587559/n04587559_4711.JPEG, got (660, 439), expect (439, 660). Please check the width/height in your annotation.
```

**Comment by liliangqi** [comment]
Hi, I got the same 'SizeMismatchError' problem when training with [config](https://github.com/facebookresearch/Detic/blob/main/configs/Detic_LbaseI_CLIP_R5021k_640b64_4x_ft4x_max-size.yaml). And I've checked the shape of image but found no bugs.

**Comment by xingyizhou** [comment]
Hi,

  Thank you for raising up this issue and thank @liliangqi for checking. I met this as well. The easiest solution would be just commenting out the error line in detectron2 and add `dataset_dict["width"], dataset_dict["height"] = image.shape[1], image.shape[0]`. This was what I did during developing the project.

  The cause of this issue is detectron2 handles the internal orientation of the image [here](https://github.com/facebookresearch/detectron2/blob/main/detectron2/data/detection_utils.py#L184), while the pre-processing script does not. This is fixed in the latest commit. Please run [tools/create_imagenetlvis_json.py](https://github.com/xingyizhou/Detic-RT/tree/master/tools/create_imagenetlvis_json.py) again and generate a new `imagenet_lvis_image_info.json`.

Best,
Xingyi

**Comment by parang99** [comment]
I could finish the training well with your help. 

Thanks!
