### ISSUE TITLE
Multi machine training error

### ISSUE THREAD

**Issue by jefferyZhan** [facebookresearch/Detic#43]
Hello~ I met a problem when I tried to train on multi machines using your code. I used two machines, each of which has eight GPUs. The error happens when loading data. The error log is shown as below. Machines can found each other. And the environment is totally the same.
`Traceback (most recent call last):
  File "/opt/conda/envs/detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/userhome/****/detectron2/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/userhome/****/Detic/train_net.py", line 261, in main
    do_train(cfg, model, resume=args.resume)
  File "/userhome/****/Detic/train_net.py", line 140, in do_train
    data_loader = build_custom_train_loader(cfg, mapper=mapper)
  File "/userhome/****/detectron2/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/userhome/****/detectron2/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/userhome/****/Detic/detic/data/custom_dataset_dataloader.py", line 59, in _custom_train_loader_from_config
    sampler = MultiDatasetSampler(
  File "/userhome/****/Detic/detic/data/custom_dataset_dataloader.py", line 217, in __init__
    seed = comm.shared_random_seed()
  File "/userhome/****/detectron2/detectron2/utils/comm.py", line 166, in shared_random_seed
    all_ints = all_gather(ints)
  File "/userhome/****/detectron2/detectron2/utils/comm.py", line 114, in all_gather
    group = _get_global_gloo_group()  # use CPU group by default, to reduce GPU RAM usage.
  File "/userhome/****/detectron2/detectron2/utils/comm.py", line 94, in _get_global_gloo_group
    return dist.new_group(backend="gloo")
  File "/opt/conda/envs/detic/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2503, in new_group
    pg = _new_process_group_helper(group_world_size,
  File "/opt/conda/envs/detic/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 588, in _new_process_group_helper
    pg = ProcessGroupGloo(
RuntimeError: [/opt/conda/conda-bld/pytorch_1614378083779/work/third_party/gloo/gloo/transport/tcp/pair.cc:769] connect [127.0.1.1]:11681: Connection refused
`
The command line is 
` python train_net.py --machine-rank 1 --num-machines 2 --num-gpus 8 --config-file configs/****** --dist-url "tcp://*****"`
Could you please help me with the error?

**Comment by xingyizhou** [comment]
Hi,

  You will need to use slurm (or other multi-machine managers) for multi-machine training. Please find my slurm scripts below (Copied from [here](https://github.com/facebookresearch/Detic/issues/22#issuecomment-1043116272)).

I used two files `train-2nodes.sh` and `multi-node_run.sh`. Run `sbatch train-2nodes.sh --config-files configs/XXXX` to start.

train-2nodes.sh

~~~
#!/bin/bash
#SBATCH -p YOUR_PARTITION
#SBATCH --nodes=2
#SBATCH --gres=gpu:8
#SBATCH --gpus-per-node=8
#SBATCH --cpus-per-task=80
#SBATCH --mem=496G
#SBATCH --time 4320
#SBATCH -o "slurm-output/slurm-%j.out"

srun multi-node_run.sh $@
~~~


multi-node_run.sh

~~~
#!/bin/bash
MASTER_NODE=$(scontrol show hostname "$SLURM_NODELIST" | head -n1)
DIST_URL="tcp://$MASTER_NODE:12399"
SOCKET_NAME=$(ip r | grep default | awk '{print $5}')
export GLOO_SOCKET_IFNAME=$SOCKET_NAME

python -u train_net.py --num-gpus 8 --num-machines 2 --machine-rank "$SLURM_NODEID" --dist-url "$DIST_URL" "$@" 
~~~
