### ISSUE TITLE
ModuleNotFoundError: No module named 'centernet'

### ISSUE THREAD

**Issue by zoldaten** [facebookresearch/Detic#65]
hello!
i`m on armv7l (raspbian Buster, raspberry pi4) with:
```
torch @ file:///home/pi/torch_1.12_wheels_armv7l/torch-1.12.0a0%2Bgita760dc2-cp37-cp37m-linux_armv7l.whl
torchvision @ file:///home/pi/torch_1.12_wheels_armv7l/torchvision-0.13.0a0%2B2ec0e84-cp37-cp37m-linux_ar
detectron2 @ git+https://github.com/facebookresearch/detectron2.git@453d795eb152f7210c842674810f24769d4dd8cb
```

but when start example:
```
python3 demo.py --config-file configs/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.yaml --input desk.jpg --output out2.jpg --vocabulary custom --custom_vocabulary headphone,webcam,paper,coffe --confidence-threshold 0.3 --opts MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth
```

got error:
```
Traceback (most recent call last):
  File "demo.py", line 20, in <module>
    from centernet.config import add_centernet_config
ModuleNotFoundError: No module named 'centernet'
```

i git cloned centernet and centernet2 and tried to installed `em with pip install -r requirements.txt
but error still exists (
how to fix or avoid ?

**Comment by 22109095** [comment]
这个问题我解决了，主要是from centernet路径的问题，全局替换，把from centernet换成from Detic.third_party.CenterNet2.centernet就行了

**Comment by rsomani95** [comment]
@zoldaten I had the same error. You'll need to clone [this repo](https://github.com/xingyizhou/CenterNet2) and put it in the folder `third_party/`

**Comment by zoldaten** [comment]
got it working ! u`re my hero! 

buy the way what is the fastest example for cpu only ? 
i have inference time 77.26s on rasberry for 1 image oO

**Comment by LeBrav** [comment]
I encounter the same error while trying to install clipfields (https://github.com/notmahi/clip-fields).

(cf) josep-bravo@CL-ROBOLAB3:~/Workspace/clip-fields$ sudo /home/josep-bravo/miniconda3/envs/cf/bin/python train.py dataset_path=nyu.r3d
Traceback (most recent call last):
  File "train.py", line 17, in <module>
    from dataloaders import (
  File "/home/josep-bravo/Workspace/clip-fields/dataloaders/__init__.py", line 3, in <module>
    from dataloaders.real_dataset import DeticDenseLabelledDataset
  File "/home/josep-bravo/Workspace/clip-fields/dataloaders/real_dataset.py", line 47, in <module>
    from centernet.config import add_centernet_config
ModuleNotFoundError: No module named 'centernet'


How can i solve it in my case?

**Comment by miao3210** [comment]
After git clone the CenterNet2 repo into the third_party folder, run
```
import sys
sys.path.insert(0, 'third_party/CenterNet2/')
```
Then we won't have bug with 
```
import centernet
```
