### ISSUE TITLE
Problem when train with lvis_v1_train+coco

### ISSUE THREAD

**Issue by wangzhengchao** [facebookresearch/Detic#78]
Hi @xingyizhou

Thank you for sharing the great work.

I am learning to train the Detic on LVIS.

The command  I used to train   python train_net.py --num-gpus 8 --config-file configs/Base-C2_L_R5021k_640b64_4x.yaml .

[09/14 03:55:46 detectron2]: Full config saved to ./output/Detic/Base-C2_L_R5021k_640b64_4x/config.yaml
[09/14 03:55:46 d2.utils.env]: Using a generated random seed 46703253
[09/14 03:55:46] timm.models.helpers WARNING: No pretrained configuration specified for resnet50_in21k model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
[09/14 03:55:46] timm.models.helpers WARNING: No pretrained configuration specified for resnet50_in21k model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
[09/14 03:55:46] timm.models.helpers WARNING: No pretrained configuration specified for resnet50_in21k model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
[09/14 03:55:46] timm.models.helpers WARNING: No pretrained configuration specified for resnet50_in21k model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
[09/14 03:55:47] timm.models.helpers WARNING: No pretrained configuration specified for resnet50_in21k model. Using a default. Please add a config to the model pretrained_cfg registry or pass explicitly.
Traceback (most recent call last):
  File "train_net.py", line 262, in <module>
    launch(
  File "/home/####/projects/detic/detectron2-main/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/####/py_venv/venv_detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/####/py_venv/venv_detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/####/py_venv/venv_detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/home/####/py_venv/venv_detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/####/projects/detic/detectron2-main/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/####/projects/detic/Detic-main/train_net.py", line 224, in main
    model = build_model(cfg)
  File "/home/####/projects/detic/detectron2-main/detectron2/modeling/meta_arch/build.py", line 22, in build_model
    model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
  File "/home/####/projects/detic/detectron2-main/detectron2/config/config.py", line 189, in wrapped
    explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
  File "/home/####/projects/detic/detectron2-main/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/####/projects/detic/Detic-main/detic/modeling/meta_arch/custom_rcnn.py", line 67, in from_config
    ret = super().from_config(cfg)
  File "/home/####/projects/detic/detectron2-main/detectron2/modeling/meta_arch/rcnn.py", line 73, in from_config
    backbone = build_backbone(cfg)
  File "/home/####/projects/detic/detectron2-main/detectron2/modeling/backbone/build.py", line 31, in build_backbone
    backbone = BACKBONE_REGISTRY.get(backbone_name)(cfg, input_shape)
  File "/home/####/projects/detic/Detic-main/detic/modeling/backbone/timm.py", line 192, in build_p67_timm_fpn_backbone
    bottom_up = build_timm_backbone(cfg, input_shape)
  File "/home/####/projects/detic/Detic-main/detic/modeling/backbone/timm.py", line 178, in build_timm_backbone
    model = TIMM(
  File "/home/####/projects/detic/Detic-main/detic/modeling/backbone/timm.py", line 127, in __init__
    self.base = create_timm_resnet(
  File "/home/####/projects/detic/Detic-main/detic/modeling/backbone/timm.py", line 86, in create_timm_resnet
    return build_model_with_cfg(
  File "/home/####/py_venv/venv_detic/lib/python3.8/site-packages/timm/models/helpers.py", line 531, in build_model_with_cfg
    model = model_cls(**kwargs) if model_cfg is None else model_cls(cfg=model_cfg, **kwargs)
  File "/home/####/projects/detic/Detic-main/detic/modeling/backbone/timm.py", line 45, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_cfg'

Thanks.

**Comment by xingyizhou** [comment]
Hi,

  This looks like a timm version issue, can you try if `pip install timm==v0.5.4` will address this?

Best,
Xingyi

**Comment by wangzhengchao** [comment]
> Hi,
> 
> This looks like a timm version issue, can you try if `pip install timm==v0.5.4` will address this?
> 
> Best, Xingyi

Thank you !  It works. And , after that , there is another problem. Maybe it is another version issue ? Thank you very much.  



[09/21 02:53:54 d2.data.build]: Using training sampler RepeatFactorTrainingSampler
Traceback (most recent call last):
  File "train_net.py", line 262, in <module>
    launch(
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/engine/launch.py", line 67, in launch
    mp.spawn(
  File "/home/wx1075382/py_venv/venv_detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/wx1075382/py_venv/venv_detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/wx1075382/py_venv/venv_detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/home/wx1075382/py_venv/venv_detic/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/engine/launch.py", line 126, in _distributed_worker
    main_func(*args)
  File "/home/wx1075382/projects/detic/Detic-main/train_net.py", line 240, in main
    do_train(cfg, model, resume=args.resume)
  File "/home/wx1075382/projects/detic/Detic-main/train_net.py", line 136, in do_train
    data_loader = build_detection_train_loader(cfg, mapper=mapper)
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/config/config.py", line 207, in wrapped
    explicit_args = _get_args_from_config(from_config, *args, **kwargs)
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/config/config.py", line 245, in _get_args_from_config
    ret = from_config_func(*args, **kwargs)
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/data/build.py", line 371, in _train_loader_from_config
    sampler = RepeatFactorTrainingSampler(repeat_factors)
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/data/samplers/distributed_sampler.py", line 147, in __init__
    seed = comm.shared_random_seed()
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/utils/comm.py", line 166, in shared_random_seed
    all_ints = all_gather(ints)
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/utils/comm.py", line 114, in all_gather
    group = _get_global_gloo_group()  # use CPU group by default, to reduce GPU RAM usage.
  File "/home/wx1075382/projects/detic/detectron2-main/detectron2/utils/comm.py", line 94, in _get_global_gloo_group
    return dist.new_group(backend="gloo")
  File "/home/wx1075382/py_venv/venv_detic/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2708, in new_group
    pg = _new_process_group_helper(group_world_size,
  File "/home/wx1075382/py_venv/venv_detic/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 630, in _new_process_group_helper
    pg = ProcessGroupGloo(
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:210] ifa != nullptr. Unable to find interface for: [::1]

**Comment by wangzhengchao** [comment]
Hi, 
Thanks for helping.
