### ISSUE TITLE
Issues with setting up environment

### ISSUE THREAD

**Issue by theophilegervet** [facebookresearch/Detic#86]
Hello,

I love your work!

I'm trying to follow these installation instructions: https://github.com/facebookresearch/Detic/blob/main/docs/INSTALL.md
But they don't work.

After following the instructions, when running
```
python demo.py --config-file configs/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.yaml --input desk.jpg --output out.jpg --vocabulary lvis --opts MODEL.WEIGHTS models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth
```
I get
```
ModuleNotFoundError: No module named 'torch.ao'
```
It seems like `torch.ao` was introduced in PyTorch 1.10, so the instructions asking for PyTorch >= 1.8 are not accurate: https://github.com/facebookresearch/d2go/issues/141

When using a later version of PyTorch (1.11), I run into another error:
```
Traceback (most recent call last):
  File "demo.py", line 140, in <module>
    demo = VisualizationDemo(cfg, args)
  File "/private/home/theop123/home-robot/src/home_robot/agent/perception/detection/detic/detic/predictor.py", line 67, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/private/home/theop123/miniconda3/envs/habitat-challenge/lib/python3.7/site-packages/detectron2/engine/defaults.py", line 288, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/private/home/theop123/miniconda3/envs/habitat-challenge/lib/python3.7/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
    ret = super().load(path, *args, **kwargs)
  File "/private/home/theop123/miniconda3/envs/habitat-challenge/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 155, in load
    checkpoint = self._load_file(path)
  File "/private/home/theop123/miniconda3/envs/habitat-challenge/lib/python3.7/site-packages/detectron2/checkpoint/detection_checkpoint.py", line 88, in _load_file
    loaded = super()._load_file(filename)  # load native pth checkpoint
  File "/private/home/theop123/miniconda3/envs/habitat-challenge/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 254, in _load_file
    return torch.load(f, map_location=torch.device("cpu"))
  File "/private/home/theop123/miniconda3/envs/habitat-challenge/lib/python3.7/site-packages/torch-1.11.0-py3.7-linux-x86_64.egg/torch/serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/private/home/theop123/miniconda3/envs/habitat-challenge/lib/python3.7/site-packages/torch-1.11.0-py3.7-linux-x86_64.egg/torch/serialization.py", line 243, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
```

What is your recommended way to get started with Detic? Would you have updated environment setup instructions?

**Comment by theophilegervet** [comment]
The second error was due to improperly downloading the checkpoint, it's resolved now, my bad.
Thanks for the awesome work!
